theme: minima
title: Polyblank Labs
header_pages:
  - README.md
  - dodger/index.md

exclude:
  - dodger/img/source
  - build_tools

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: home
